site_name: maite-models
site_url: !ENV [MKDOCS_SITE_URL, "https://gitlab.jatic.net/jatic/orchestration-interoperability/maite-models"]

use_directory_urls: false

theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: indigo

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
